### ISSUE TITLE
Don't use :default when publishing libraries

### ISSUE THREAD

**Issue by thheller** [dvingo/cljs-styled-components#1]
You are using

```
["styled-components" :default styled :refer [keyframes ThemeProvider]]
```

which is currently only supported in `shadow-cljs` and breaks when using other CLJS tools due to the `:default`. You should replace this with

```
["styled-components" :refer [default keyframes ThemeProvider] :rename {default styled}]
```

instead. This will be compatible with all tools.

You can vote for `:default` here: https://dev.clojure.org/jira/browse/CLJS-2376

**Comment by dvingo** [comment]
Apologies for the _very_ late reply! 
I just deployed an update, `0.1.5` is using the `:rename` syntax now.
