### ISSUE TITLE
Cannot import reagent sub-package

### ISSUE THREAD

**Issue by philip-peterson** [dvingo/cljs-styled-components#19]
Hello there, thank you for making this package.

I was attempting to use it today and found that importing the reagent subpackage (per docs) seems to not work so well when compiling:

```
Unexpected error (ExceptionInfo) compiling at (REPL:1).
No such namespace: cljs-styled-components.reagent, could not locate cljs_styled_components/reagent.cljs, cljs_styled_components/reagent.cljc, or JavaScript source providing "cljs-styled-components.reagent" (Please check that namespaces with dashes use underscores in the ClojureScript file name) in file
```

Reproduction steps: 

1. [Github link to repro case here](https://github.com/philip-peterson/clojure-reagent-starter-kit/commit/9db4de52ce6ea1c36ae3f1fb92a4bfb2aa7ae386#diff-b7ac8da9626701ac68ce9e38267c9a4c8c073cdf48d332f579dace2c42abcbc8R7)
2. `clj -M -m cljs.main -co build.edn -v -c -r `

Thanks for your time. Cheers!
Philip

**Comment by dvingo** [comment]
Hi thanks for the report and reproduction project.

There were a couple issues with your project setup, but there was also a bug with the cljs-styled-components lib.
I fixed the lib error with version `0.1.12`

The project errors are:
- `deps.edn` syntax errors, this is what I changed it to:
```clojure
 {:deps {org.clojure/clojurescript {:mvn/version "1.11.54"}
         com.bhauman/figwheel-main {:mvn/version "0.2.18"}
         reagent/reagent {:mvn/version "1.1.1" :exclusions [cljsjs/react cljsjs/react-dom]}
         cljs-styled-components/cljs-styled-components {:mvn/version "0.1.12"}}
  :paths ["src" "target" "resources"]
  :aliases {:dev {:extra-deps []}}}
```
and in `todo-mvc.core`
```clojure
(defn todo-app []
  [:div [example1 "hello world"]])
```
then it works:
<img width="145" alt="image" src="https://user-images.githubusercontent.com/467827/193326882-26041202-d77c-49b5-9c08-dd7cad89d9b1.png">
