### ISSUE TITLE
Migrate away from extends api

### ISSUE THREAD

**Issue by dpsutton** [dvingo/cljs-styled-components#2]
styled components have deprecated and removed the extend api which is used to extend other styled components. As such this library doesn't work with the current version 4.0+.

**Comment by dvingo** [comment]
Thanks for the heads up! I'm working on an update now. Not using `extends` anymore was a simple change, but they also updated the keyframes/animation API so I need to rework that as well. Should have a new release shortly.

**Comment by dvingo** [comment]
@dpsutton I just published version 0.1.6 to work with v4, that removes use of extends. There is also a breaking change (notes in the readme) regarding the use of animations to add support for the v4 animations code in styled components.
