### ISSUE TITLE
Adding specificity via cljs-styled-components

### ISSUE THREAD

**Issue by alexdao3** [dvingo/cljs-styled-components#3]
Oftentimes we use `styled-components` to wrap a React component from a 3rd-party library. The 3rd party library may have its own styles applied, and based on how those styles are defined, the CSS specificity from 3rd-party libraries might override the styles defined in my styled-component.

In styled-components JS, we often use this trick to increase specificity of our styles. Is this possible via cljs-styled-components?

https://www.styled-components.com/docs/faqs#how-can-i-override-styles-with-higher-specificity

**Comment by dvingo** [comment]
Hi @alexdao3 - yep, I just tried it out and using the ampersand technique works as expected:

```clojure
(defstyled first-component :div
           {"backgroundColor" "slategrey"})

(defstyled second-component first-component
  {"&&&"
    {"backgroundColor" "purple"}})

;; in your render code:
[second-component "some text"]
```
Here is how it looks in chrome devtools:

![cljs_styled_example](https://user-images.githubusercontent.com/467827/64378041-cd51b080-cff9-11e9-8d3b-b6f29e9342e4.png)

**Comment by alexdao3** [comment]
@dvingo Awesome, thanks!
