### ISSUE TITLE
Working with Styled System syntax

### ISSUE THREAD

**Issue by danchristian** [dvingo/cljs-styled-components#4]
Does this work with [Styled System](https://styled-system.com)? The string interpolation syntax within the template literal is:

```
import styled from 'styled-components'
import { color } from 'styled-system'

const Box = styled.div`
  ${color}
`
```

I'm not totally sure how that would be represented?

**Comment by danchristian** [comment]
I manged to get this working with [Style Mixins](https://github.com/dvingo/cljs-styled-components/#js-objects).

`(defstyled button :button {:styled/mixins [color]})`

**Comment by dvingo** [comment]
Ah nice find - I'm wondering if doing:
```clojure
(defstyled button :button [color])
```
should work as well - right now it doesn't as there is only support for inline objects (where `color` would be a js object) I'll leave it for now, but will keep it in mind.
