### ISSUE TITLE
Support createGlobalStyle helper function

### ISSUE THREAD

**Issue by danchristian** [dvingo/cljs-styled-components#6]
With `v4` of Styled Components there is a [helper function](https://www.styled-components.com/docs/api#createglobalstyle) to handle global styles. This doens't use the regular `const Box = styled.div` syntax but rather `const GlobalStyle = createGlobalStyle`. It would be good if we could do something like `(defglobalstyle global-style`.

**Comment by dvingo** [comment]
That makes sense. Should be easy enough to add.

**Comment by dvingo** [comment]
Hi @danchristian I just deployed version "0.1.9" to clojars which adds support for `defglobalstyle`. I also tested it out in a reagent app and the global class name is working as expected.
